             - name: Generate snake game from GitHub contribution grid
        uses: Platane/snk@v3
        with:
          github_user_name: chaitanyamodi-dev
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=ffffff&color_dots=1a1a2e,4c1d95,6d28d9,8b5cf6,a855f7
            dist/github-contribution-grid-snake-dark.svg?color_snake=ffffff&color_dots=1a1a2e,4c1d95,6d28d9,8b5cf6,a855f7
